---
apiVersion: v1
kind: ConfigMap
metadata:
  name: od-config
  namespace: {{ .Values.namespace.name }}
  labels:
    app: open-design
    app.kubernetes.io/part-of: open-design
data:
{{- range $key, $value := .Values.opendesign.config }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
