---
apiVersion: v1
kind: Service
metadata:
  name: open-design-svc
  namespace: {{ .Values.namespace.name }}
  labels:
    app: open-design
    app.kubernetes.io/component: daemon
    app.kubernetes.io/part-of: open-design
spec:
  selector:
    app: open-design
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.opendesign.service.port }}
      targetPort: 7457
      {{- if and (eq .Values.opendesign.service.type "NodePort") .Values.opendesign.service.nodePort }}
      nodePort: {{ .Values.opendesign.service.nodePort }}
      {{- end }}
  type: {{ .Values.opendesign.service.type }}
